### PR TITLE
added ssh client to container build.

### PR DESCRIPTION
**Pull request by mubeta06**
This PR see the addition of an ssh client to make using remote modules from private repos using the git+ssh scheme possible.

### CODE REVIEW

**Comment by sjauld** [comment]
This would be spectacularly helpful!

**Comment by sjauld** [comment]
Looks like we're a duplicate of #30

**Comment by catsby** [comment]
Merged #30 , thanks!

**Comment by shederman** [comment]
Question: how do you get the SSH keys for the git repos you will pull onto the container in a secure fashion?

**Comment by sjauld** [comment]
You can just forward in the agent if you're on linux. For macos, I think you have to forward in the entire .ssh folder. For windo$e, no idea!

`docker run --rm -it -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro hashicorp/terraform apply`

**Pull request closed without merging**
