### PR TITLE
Dockerfile Improvements

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @mitchellh @catsby @mwhooker guys would you like to help review this PR? Thanks.

**Comment by SwampDragons** [comment]
We took long enough to get to this that the branch is nice and stale -- it was easier for me to cherry-pick your relevant commits and fix them one at a time, so that's what I did. Thanks for this, and sorry it took so long to incorporate 😬

**Comment by PeterDaveHello** [comment]
@SwampDragons anything I need to do here? Looks like not all the commits were picked, would you like me to revise any of them?

**Comment by SwampDragons** [comment]
the terraform dockerfiles no longer live in this repo, so I didn't pick them. The ENV adjustment didn't seem to have any effect on final file size, and confused the deploy script, so I didn't take that one either. I think I got the rest of them, so I don't think there's anything to revise.

**Pull request closed without merging**
