### PR TITLE
Add baseline vault dockerfiles for inclusion.

### PR DESCRIPTION
**Pull request by sylus**
Got excited at the prospect of having official hashicorp images for vault. I just followed the original pattern thus far. 

Eventually is the plan to support multiple versions so the folder structure would be?

vault
       0.5
             dockerfile
       0.6
             dockerfile

### CODE REVIEW

**Comment by timfallmk** [comment]
Hey @sylus ! Glad you're excited about vault images. We've actually been working on these internally (along with the other major tools). Let me review your PR and see if I can incorporate it. Stand by for more news! ⚡

**Comment by sylus** [comment]
Awesome thanks a bunch!

If the P.R. doesn't align with what you have already feel free to close. ^_^

**Comment by arminc** [comment]
What's the status on this?

**Comment by sylus** [comment]
Just closing out outdated P.R. :)

**Pull request closed without merging**
